### PR TITLE
fix #136 - Allow ROMA checks `tchmgr`installed in customised place

### LINKED ISSUE #136: Allow ROMA checks `tchmgr`installed in customised place
(This is for recording the discussion in

> https://github.com/roma/roma/pull/135

and to make it as an issue like others.)

Now the test `test_check_tc_flag` gives a fixed path of where the `tchmgr` should be. Unfortunately, if the installation is from other package manager like `apt-get` in Ubuntu, the check will fail, although it still has the valid binary file. To solve this, the test could firstly try to seek for the system-widely installation, and then go back to use the assumed path after it fails. In this way, we can also fix the Travis failure by adding an extra apt package in `.travis.yml`.

### PR DESCRIPTION
**Pull request by snowmantw**
As the discussion in

> https://github.com/roma/roma/pull/135

this is the patch to fix the Travis failure and allow ROMA to check `tchmgr` in different places rather than the default one. I will close the old WIP PR if this get review+.

### CODE REVIEW

File: test/t_new_func.rb [hunk 1]
```diff
@@ -365,7 +365,18 @@ def test_check_tc_flag
...
     stop_roma
-    res = `#{bin_dir}/check_tc_flag --storage ./localhost_11211/roma --library /usr/local/roma/libexec`
+
+    # If `tchmgr` is system-widley known, like installation from `apt-get`,
+    # set the library path as it's parent directory.
+    #
+    # If not, assume it is under the libexec directory.
+    path_tchmgr = `which tchmgr`
+    libpath = Pathname.new(path_tchmgr).dirname.each_filename.to_a[0..-2]
+              .join(File::Separator).prepend(File::Separator) if "" != path_tchmgr
```
Comment (satoryu) [inline test/t_new_func.rb]: umm, this line looks unreadable to me. 
This line attempts to extract the path to the directory in which `bin/tchmgr` are, doesn't it?
It can be done with `File.expand_path(File.join(path_tchmgr, '..', '..'))`.

Comment (snowmantw) [inline test/t_new_func.rb]: Ah, good idea. I'll update the PR ASAP. Thanks.

**Comment by snowmantw** [comment]
Hi @satoryu , I've updated the patch as you suggested. If you feel it's good, you may merge it at a good time. Thanks.

**Comment by satoryu** [comment]
Thank you for your great work!

**Comment by snowmantw** [comment]
You're welcome!
